# -----------------------------------------------
# Jekyll Configuration
# -----------------------------------------------

name:       Paul Van Tuyl
gems:       jekyll-redirect-from
permalink:  pretty
include:    [".htaccess"]
exclude:    ["less", "README.markdown", "CNAME"]
timezone:   America/Phoenix
markdown:   kramdown
kramdown:
   input:   GFM

# -----------------------------------------------
# Site-specific Settings
# -----------------------------------------------

author:         Paul Van Tuyl
author_email:   paulvantuyl@gmail.com
